# Generated by Django 2.1.2 on 2018-11-22 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_member_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='file',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
    ]
